### ISSUE TITLE
Create authentication

### ISSUE THREAD

**Issue by amjcosta** [codeforgoodconf/black_holes_frontend#2]
Set up a way for users to log in to their account.

**Comment by sauln** [comment]
Is this separate from building out the user model? I was thinking about adding specifics about bulking out a user and vote model but maybe it should be its own issue.  What do you all think?

I imagine it would look something like this:

- [ ] Create a user model
   - Model should track user information as well as have information about which galaxies they have seen and what they said.  
- [ ] Create a vote model
   - Model should link a user and a galaxy as well as contain information of the vote (yes/no for affirm or original label)

**Comment by sauln** [comment]
Kamino closed and cloned this issue to codeforgoodconf/black_holes
