### ISSUE TITLE
make sure machine and human labels are consistent!!!

### ISSUE THREAD

**Issue by edbreeden** [codeforgoodconf/black_holes_frontend#8]
I'm pretty sure that right now the humans input True if there **IS** a WR bump [meaning **NOT** a blackhole] and the machine marks galaxies as True if there is **NO** WR bump [meaning it **IS** a blackhole]. lets please make sure it does not do this before we use the app to train the computer!!! idk who is working on this project still but you guys can assign me if you want me to do it and ill change the html on the app to make sure it's clear and consistent.

- **Also** unrelated side note: I probably can't video conference with the client but you should ask him if he has a written description to put on the front page or any info for the about page so one of us can through it in there :)

**Comment by edbreeden** [comment]
^ accidental close -_-

**Comment by sauln** [comment]
Kamino closed and cloned this issue to codeforgoodconf/black_holes
